### ISSUE TITLE
conda build failing under Windows 10, due to unresolved version.

### ISSUE THREAD

**Issue by capn-freako** [enthought/chaco#817]
**Problem Description**

When trying to `conda build` _chaco_ under Windows 10, I'm getting the following error:

>     RuntimeError: Unable to determine package version. No local Git clone detected, and no version file found at C:\Users\capnf\AppData\Local\Temp\pip-req-build-825e1krg\chaco\_version.py.
 
**Reproduction Steps:**

Checkout "5.0.0" and attempt a `conda build`, using the following recipe (i.e. - `meta.yaml`):

```
{% set name = "chaco" %}
{% set version = "5.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../chaco/

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - vs2019_win-64
  
  host:
    - python
    - enable
    - Cython

  run:
    - python
    - enable
```

```python
# Code to reproduce issue here
```

**Expected behavior:**

I expect the `conda build` to succeed.

**OS, Python version:** [Enter OS name and Python version]

Windows 10
Python 3.7
